---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Hosts: where our play will run and options it will run with
  hosts: localhost
 
  # Vars: variables that will apply to the play, on all target systems
  # vars:
  #   motd_centos: "Welcome to CentOS Linux - Ansible Rocks\n"
  #   motd_ubuntu: "Welcome to Ubuntu Linux - Ansible Rocks\n"
  vars_files:
    - launch_ip.yaml 
 
  # Tasks: the list of tasks that will be executed within the playbook
  tasks:

  - name: Debug Message on the iteration
    debug:
      msg: "Iterating over {{ kubernetes_master.launch_ip }}"
    when: ansible_distribution == "Ubuntu"

  - name: Check the distribution then call relevant containerd tasks
    include_tasks: containerd.yaml
    when: ansible_distribution == "Ubuntu"
    with_items: "{{ kubernetes_master.launch_ip }}"
 
  # Handlers: the list of handlers that are executed as a notify key from a task
  # handlers:
  #   - name: MOTD changed
  #     debug:
  #       msg: The MOTD was changed
 
  # Roles: list of roles to be imported into the play
 
# Three dots indicate the end of a YAML document
...
